permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

# 作者信息
author: 
  name: hacpai
  email: iomniscience@icloud.com
  link: http://hacpai.github.io/simpleblog
  weibo: http://weibo.com/u/2954068011
  github: http://github.com/hacpai

# 站点信息
title: hacpai's blog
description: hacpai's blog
url: http://hacpai.github.io/simpleblog
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-66883716-1
  url: hacpai.github.io/simpleblog

# disqus 设置
disqus:
  shortname: hacpaissimpleblog
